services:
  lengthprice:
    class: LengthPrice
    factory: [ 'Module', 'getInstanceByName' ]
    arguments:
      - 'lengthprice'
    public: true

  prestashop.module.lengthprice.service.product_settings:
    class: PrestaShop\Module\LengthPrice\Service\LengthPriceProductSettingsService
    public: true
    arguments:
      - '@lengthprice'

  prestashop.module.lengthprice.db_instance:
    class: Db
    factory: [ 'Db', 'getInstance' ]
    public: true

  prestashop.module.lengthprice.service.cart:
    class: PrestaShop\Module\LengthPrice\Service\CartService
    public: true
    arguments:
      - '@lengthprice'
      - '@prestashop.module.lengthprice.db_instance'
      - '@prestashop.adapter.legacy.context'

  prestashop.module.lengthprice.repository.cart: # Nazwa serwisu
    class: PrestaShop\Module\LengthPrice\Repository\LengthPriceCartRepository
    public: true # lub false, jeśli tylko inne serwisy mają go używać
    arguments:
      - '@lengthprice' # Wstrzyknij instancję modułu (lub translator, jeśli zmienisz)
      - '@prestashop.module.lengthprice.db_instance' # Wstrzyknij serwis Db

  PrestaShop\Module\LengthPrice\Controller\Admin\AdminLengthPriceSettingsController:
    class: PrestaShop\Module\LengthPrice\Controller\Admin\AdminLengthPriceSettingsController
    public: true
    arguments:
      - '@lengthprice' # Wstrzyknij serwis modułu
      - '@prestashop.module.lengthprice.service.product_settings'
      - '@translator'
    tags: [ 'controller.service_arguments' ]